import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactQueryClientProvider } from "@/src/app/context/ReactQueryClientProvider";
import { Header } from "@/src/widgets/header/ui/Header";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryClientProvider>
        <body className={`${roboto.className}  antialiased`}>
          <Header />
          {children}
        </body>
      </ReactQueryClientProvider>
    </html>
  );
}
